Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2020-05, with the labels that each got.

#87 Improve csi-snapshotter ClusterRole
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-snapshotter.yaml
Labels: needs/ok-to-test

#92 Revert "Add validator target for CICD compatibility"
  Dockerfile
Labels: needs/ok-to-test

#90 Support add custom label on GCP compute engine vm
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test

#93 [ci:component:github.com/gardener/machine-controller-manager:v0.27.0->v0.28.0]
  charts/images.yaml
Labels: needs/ok-to-test

#94 Vendor gardener/gardener@v1.4.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/types.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/constraints_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/github.com/gardener/gardener/pkg/utils/validation/cidr/disjoint.go
  vendor/modules.txt
Labels: needs/ok-to-test

#95 Use Terraform resource timeouts and workqueue backoff
  charts/internal/gcp-infra/templates/main.tf
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#96 Prevent errors to be logged multiple times
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: needs/ok-to-test

#97 [ci:component:github.com/gardener/machine-controller-manager:v0.28.0->v0.29.0]
  charts/images.yaml
Labels: needs/ok-to-test

#99 Use cloud-controller-manager v1.18
  charts/images.yaml
Labels: needs/ok-to-test

#101 Vendor gardener/gardener@4949b41172cc35f6fecf920d6f7151b24562ae75
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/pkg/features/features.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/features/features.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/crds.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/ingress_gateway.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/istiod.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/type.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#102 Vendor gardener/gardener@28def0ceecf15f5c7323cd5e65300adc0b0c81da
  cmd/gardener-extension-provider-gcp/app/app.go
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#103 Vendor gardener/gardener@v1.5.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#104 Fix status.lastError.codes for Infrastructure
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#105 Vendor gardener/gardener@v1.5.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/botanist.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/cleanup.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/containerruntime.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/dns/dnsentry.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/dns/dnsprovider.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/extension.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/infrastructure.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/network.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/waiter.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/worker.go
  vendor/github.com/gardener/gardener/pkg/operation/common/extensions.go
  vendor/github.com/gardener/gardener/pkg/operation/operation.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/pkg/utils/retry/retry.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/modules.txt
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal
