Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2020-10, with the labels that each got.

#181 Enhance chart options
  Dockerfile
  charts/gardener-extension-provider-gcp/templates/deployment.yaml
  charts/gardener-extension-provider-gcp/templates/vpa.yaml
  charts/gardener-extension-provider-gcp/values.yaml
  example/controller-registration.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#182 Add k8s 1.19 conformance tests (testgrid) links
  README.md
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#188 Upgrade github.com/gardener/cloud-provider-gcp
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#189 add priority class for extension pods
  charts/gardener-extension-provider-gcp/templates/_helpers.tpl
  charts/gardener-extension-provider-gcp/templates/deployment.yaml
  charts/gardener-extension-provider-gcp/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#192 Do no longer ignore deprecated item usage
  .golangci.yaml
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#193 Revert machine drainTimeout to 2hrs from 12hrs
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: area/ops-productivity, kind/regression, needs/ok-to-test, platform/gcp, priority/critical, reviewed/lgtm, size/xs

#194 Cherrypick: Revert machine drainTimeout to 2hrs from 12hrs
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
Labels: area/ops-productivity, kind/regression, needs/ok-to-test, platform/gcp, priority/critical, size/xs
