Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2020-12, with the labels that each got.

#214 Remove deprecated role label key from components
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
Labels: kind/cleanup, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#216 Fix release test run
  .ci/test-integration.sh
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#217 Readd role label key to pod template of mcm and ccm
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#220 Update kubernetes-csi/external-snapshotter to v2.1.3
  charts/images.yaml
Labels: area/storage, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#223 Vendor gardener/gardener@f6b4e24
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/mapper.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/cmd/factory.go
  vendor/github.com/gardener/gardener/hack/install-requirements.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/logging.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/namespaces.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/seedsystemcomponents/seedadmission/logging.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/graph.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/bootstrap_token.go
  vendor/github.com/gardener/gardener/test/framework/common.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs

#224 Update README.md with versions that are no longer actively tested
  README.md
Labels: area/documentation, needs/ok-to-test, reviewed/lgtm, size/xs
