Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2020-11, with the labels that each got.

#195 Vendor to gardener v1.12.3
  .test-defs/infrastructure-test.yaml
  Dockerfile
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/terraformer.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/helper/shootstate_list.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go
  vendor/github.com/gardener/gardener/pkg/mock/gardener/extensions/terraformer/mocks.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/addons.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/botanist.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/logging.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/monitoring.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/monitoring_alertingrules.test.yaml
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/shoot_resources.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/waiter.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/monitoring.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/waiter.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/wanted_secrets.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/shoot/types.go
  vendor/github.com/gardener/gardener/pkg/operation/shootsecrets/secrets_manager.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/taskfn.go
  vendor/github.com/gardener/gardener/test/framework/gardener_utils.go
  vendor/github.com/gardener/gardener/test/framework/gardenerframework.go
  vendor/github.com/gardener/gardener/test/framework/seedregistrationframework.go
  vendor/github.com/gardener/gardener/test/framework/shoot_utils.go
  vendor/modules.txt
Labels: needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#196 Network: use the shoot iprange to replace hardcode
  charts/internal/gcp-infra/templates/main.tf
Labels: area/networking, kind/bug, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#197 Fix "make test" on macOS
  go.mod
  go.sum
  vendor/github.com/gobuffalo/packr/v2/SHOULDERS.md
  vendor/github.com/gobuffalo/packr/v2/go.mod
  vendor/github.com/gobuffalo/packr/v2/go.sum
  vendor/github.com/gobuffalo/packr/v2/version.go
  vendor/github.com/karrick/godirwalk/bench.sh
  vendor/github.com/karrick/godirwalk/readdir_unix.go
  vendor/github.com/karrick/godirwalk/scandir_unix.go
  vendor/modules.txt
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#198 Changing the default parameters handling and adding all properties to the test definition
  .test-defs/provider-gcp.yaml
  test/tm/generator.go
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/s

#199 Error wrapping for UpdateMachineImagesStatus function
  pkg/controller/worker/machine_images.go
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#190 Adapt infrastructure actuator to terraformer@v2
  charts/images.yaml
  pkg/internal/terraform.go
Labels: area/quality, area/robustness, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#201 add rate limit to documentation
  docs/usage-as-end-user.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#202 Fix infrastructure integration test
  test/integration/infrastructure/infrastructure_test.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#205 [manual:component:github.com/gardener/terraformer:v1.5.0->v2.0.0]
  charts/images.yaml
Labels: area/quality, area/robustness, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#209 Switch to gcr base images
  Dockerfile
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/xs

#208 Cleanup terraformer usage
  go.mod
  go.sum
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_migrate.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/infrastructure/actuator_restore.go
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
  pkg/internal/terraform.go
  test/integration/infrastructure/infrastructure_test.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/errors.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/state.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/terraformer.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/waiter.go
  vendor/github.com/gardener/gardener/pkg/mock/gardener/extensions/terraformer/mocks.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/addons.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/cleanup.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/interfaces.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/clusterautoscaler/bootstrap.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/bootstrap.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go
  vendor/github.com/gardener/gardener/pkg/operation/garden/garden.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/types.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/patch.go
  vendor/github.com/gardener/gardener/test/framework/common.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/github.com/gardener/gardener/test/framework/shoot_utils.go
  vendor/github.com/gardener/gardener/test/framework/shootframework.go
  vendor/modules.txt
Labels: area/logging, area/quality, kind/cleanup, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/m

#211 Prepare Next Dev Cycle v1.13.1-dev
  VERSION
  example/controller-registration.yaml
Labels: area/dev-productivity, kind/impediment, needs/review, platform/gcp, priority/critical, reviewed/ok-to-test, size/xs

#212 Cherrypick pr206 & pr210 to v0.13
  Dockerfile
  charts/images.yaml
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/gcp, priority/critical, reviewed/lgtm, size/xs

#213 Run infra integration test on release
  .ci/pipeline_definitions
  .ci/test-integration.sh
  .ci/testruns/default/Chart.yaml
  .ci/testruns/default/templates/testrun.yaml
  .ci/tm-config.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/s

#215 Vendor gardener/gardener@4fcecc0519dd
  .github/pull_request_template.md
  go.mod
  go.sum
  pkg/controller/worker/machine_controller_manager.go
  test/e2e/networkpolicies/networkpolicy_test.go
  vendor/github.com/gardener/gardener/.github/pull_request_template.md
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/interface.go
  vendor/github.com/gardener/gardener/extensions/test/e2e/framework/networkpolicies/agnostic.go
  vendor/github.com/gardener/gardener/hack/.ci/set_dependency_version
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/clusterautoscaler/cluster_autoscaler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/etcd/etcd.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubecontrollermanager/kube_controller_manager.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane/kubescheduler/kube_scheduler.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/modules.txt
Labels: kind/task, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm, size/s
