Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2020-09, with the labels that each got.

#165 Update kubernetes-sigs/gcp-compute-persistent-disk-csi-driver to v1.0.1
  charts/images.yaml
Labels: area/storage, kind/task, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#168 Cleanup make test
  Makefile
Labels: kind/cleanup, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#167 Support for Kubernetes 1.19
  Makefile
  README.md
  charts/images.yaml
Labels: area/open-source, area/usability, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#169 Change volumeBindingMode to WaitForFirstConsumer
  charts/internal/shoot-storageclasses/templates/storageclasses_legacy.yaml
Labels: area/storage, kind/task, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#170 Updated RBAC to allow node/status update by MCM
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#173 Webhook ensurer does not remove or add /etc/ssl directory for kube apiserver deployments
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#175 Migration from in-tree to out-of-tree MCM controllers
  charts/images.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machineclass/templates/machineclass.yaml
  pkg/controller/worker/machine_controller_manager.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/gcp/types.go
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#179 Vendor gardener/gardener@v1.10.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/predicate.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/state_actuator.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/admissionplugins.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/miscellaneous.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/types.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/operation.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/types.go
  vendor/github.com/gardener/gardener/pkg/operation/types.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/flow.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_delaying.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_immediate.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/modules.txt
Labels: area/scalability, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm

#178 add minAllowed for machine-controller-manager-vpa
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
Labels: area/auto-scaling, area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, priority/normal, reviewed/lgtm
