Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2021-07, with the labels that each got.

#286 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#287 Make leader election resource lock configurable and default to leases
  charts/gardener-extension-provider-gcp/templates/deployment.yaml
  charts/gardener-extension-provider-gcp/values.yaml
  cmd/gardener-extension-provider-gcp/app/app.go
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#294 Set minAllowed memory for csi-driver-node containers
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, needs/review, platform/gcp, size/xs

#293 Clean up handling for unsupported K8s versions
  README.md
  charts/gardener-extension-provider-gcp/templates/_helpers.tpl
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/_helpers.tpl
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/shoot-storageclasses/templates/_helpers.tpl
  charts/internal/shoot-storageclasses/templates/storageclasses_legacy.yaml
  example/10-fake-shoot-controlplane.yaml
  example/30-controlplane.yaml
  example/30-worker.yaml
  example/controller-registration.yaml
  pkg/controller/controlplane/valuesprovider_test.go
Labels: kind/cleanup, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#300 Expose MCM logs to the end-users
  charts/gardener-extension-provider-gcp/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#301 Update kubernetes-csi/external-provisioner
  charts/images.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
Labels: area/storage, kind/test, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#305 Add release milestone check action
  .github/workflows/release-milestone.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#304 Updated MCM RBACs to support VolumeAttachments
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
Labels: area/dev-productivity, kind/api-change, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs
