Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2021-04, with the labels that each got.

#251 Fix the infrastructure-test TestDefinition
  .test-defs/infrastructure-test.yaml
  .test-defs/provider-gcp.yaml
Labels: kind/bug, kind/test, needs/ok-to-test, reviewed/lgtm, size/xs

#252 Update kubernetes-csi/external-snapshotter
  charts/images.yaml
Labels: area/storage, kind/enhancement, kind/test, needs/ok-to-test, reviewed/lgtm, size/xs

#257 depend on publish trait rather than injected step(s)
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#254 Specify container resources for CSI sidecars
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#256 Switch to kaniko oci builder
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#253 Use client.Reader to prevent starting Informer for Secrets
  cmd/gardener-extension-admission-gcp/app/app.go
  hack/dev-setup-admission-gcp.sh
  pkg/admission/validator/shoot.go
Labels: needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#260 Decrease terraformer log level
  pkg/internal/terraform.go
Labels: kind/test, needs/ok-to-test, reviewed/lgtm, size/xs
