Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2021-08, with the labels that each got.

#296 Add validation for min # of worker machines in shoot
  docs/usage-as-end-user.md
  pkg/admission/validator/shoot.go
  pkg/apis/gcp/validation/shoot.go
  pkg/apis/gcp/validation/shoot_test.go
  pkg/apis/gcp/validation/worker_test.go
Labels: kind/enhancement, kind/test, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/m, area/auto-scaling, merge/squash

#297 Update kubernetes-csi/external-snapshotter to v3.0.3
  charts/images.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml
  charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xl

#307 Upgrade github.com/gardener/cloud-provider-gcp
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#308 Upgrade github.com/gardener/cloud-provider-gcp
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#315 Add Kubernetes v1.21 conformance badge
  README.md
Labels: needs/ok-to-test

#318 Stop using `github.com/pkg/errors`
  go.mod
  pkg/apis/gcp/helper/scheme.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/controller/worker/helper.go
  pkg/controller/worker/machine_images.go
  pkg/controller/worker/machines.go
  pkg/webhook/controlplaneexposure/ensurer.go
  test/tm/generator.go
  vendor/modules.txt
Labels: kind/cleanup, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s
