Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2021-05, with the labels that each got.

#266 Fix support for multiple .networks.cloudNAT.natIPNames
  charts/internal/gcp-infra/templates/main.tf
Labels: kind/bug, kind/test, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#267 [release-v1.16] Automated cherry pick of #266: Fix support for multiple .networks.cloudNAT.natIPNames
  charts/internal/gcp-infra/templates/main.tf
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#268 Replace terraformer's helm chart with go templates
  charts/internal/gcp-infra/Chart.yaml
  charts/internal/gcp-infra/templates/main.tf
  charts/internal/gcp-infra/values.yaml
  go.mod
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/internal/infrastructure/template.go
  pkg/internal/infrastructure/templates/main.tpl.tf
  pkg/internal/infrastructure/templates/terraform.tfvars
  pkg/internal/infrastructure/templates/variables.tf
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
  vendor/modules.txt
Labels: area/control-plane, kind/cleanup, kind/test, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xl

#271 Update ClusterRoles for MCM
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
Labels: area/delivery, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#274 [release-v1.16] Automated cherry pick of #270: [ci:component:github.com/gardener/machine-controller-manager-provider-gcp:v0.4.0->v0.5.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#273 [release-v1.16] Automated cherry pick of #269: [ci:component:github.com/gardener/machine-controller-manager:v0.38.0->v0.39.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#276 Vendor gardener/gardener@v1.23.1
  example/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/charts/images.yaml
  vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#277 Expose logs from user exposed components in the new way
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/configmap-observability.yaml
Labels: area/logging, kind/enhancement, kind/test, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs
