Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2022-01, with the labels that each got.

#371 `make generate` for the year change
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/v1alpha1/zz_generated.defaults.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/gcp/v1alpha1/zz_generated.defaults.go
  pkg/apis/gcp/zz_generated.deepcopy.go
Labels: needs/ok-to-test

#375 Do not use err (always `nil`) in error message
  pkg/controller/bastion/options.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#370 fix bastion test
  pkg/controller/bastion/actuator_delete.go
  test/integration/bastion/bastion_test.go
Labels: kind/test, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#377 Update RBAC for leader election of `machine-controller-manager`
  charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#374 Add check for the docforge manifest
  .ci/verify
  .gitignore
  Makefile
  hack/tools/bin/.gitkeep 
Labels: area/documentation, kind/enhancement, platform/gcp, reviewed/lgtm, size/xs

#372 Update kubernetes-sigs/gcp-compute-persistent-disk-csi-driver to v1.3.4
  charts/images.yaml
Labels: area/storage, kind/impediment, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#382 Kubernetes Version Configurability per Worker Pool
  docs/usage-as-end-user.md
  pkg/apis/gcp/validation/shoot.go
  pkg/apis/gcp/validation/shoot_test.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/csimigration/add.go
  pkg/controller/healthcheck/add.go
  pkg/gcp/types.go
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/m, merge/squash
