Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2022-05, with the labels that each got.

#430 add k8s v1.23 conformance testgrid link
  README.md
Labels: area/certification, kind/test, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#427 Remove deprecated dashboards
  charts/internal/seed-controlplane/charts/cloud-controller-manager/ccm-dashboard.json
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/csi-driver-controller-dashboard.json
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/configmap-observability.yaml
Labels: area/logging, kind/cleanup, needs/ok-to-test, needs/review, needs/second-opinion, platform/gcp, size/xl

#405 Update manifest.yaml
  .docforge/manifest.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#437 Upgrade github.com/gardener/cloud-provider-gcp
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#432 Adjust component resources request and limits
  charts/gardener-extension-admission-gcp/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-provider-gcp/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/vpa.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
  cmd/gardener-extension-provider-gcp/app/app.go
  example/controller-registration.yaml
  pkg/controller/controlplane/valuesprovider.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/m

#439 Use external-provisioner@v2.1.0 for K8s `< 1.22`
  charts/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#440 [release-v1.22] Automated cherry pick of #439: Use external-provisioner@v2.1.0 for K8s `< 1.22`
  charts/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#428 admission-gcp: Add SecretBinding validator
  charts/gardener-extension-admission-gcp/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-gcp/charts/application/templates/validatingwebhook-validator.yaml
  example/40-validatingwebhookconfiguration.yaml
  pkg/admission/validator/secretbinding.go
  pkg/admission/validator/secretbinding_test.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/validator_suite_test.go
  pkg/admission/validator/webhook.go
  pkg/apis/gcp/validation/shoot_test.go
  pkg/apis/gcp/validation/worker_test.go
Labels: area/cost, area/robustness, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/m

#442 Fix csi-driver-node VPA
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#444 Support for Kubernetes v1.24
  README.md
  charts/images.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/checkerwatchdog.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/checkerwatchdogfactory.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/watchdogmanager.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/secret/manager/manager.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/certificates/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/certificates/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/cmd/options.go
  vendor/github.com/gardener/gardener/hack/test-integration.sh
  vendor/github.com/gardener/gardener/hack/tools.mk
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/types.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/healthz/periodic.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_delaying.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/seed.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/unstructured/object.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/alias.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/certificate.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/manager/manager.go
  vendor/github.com/gardener/gardener/pkg/utils/validation/features/featuregates.go
  vendor/github.com/gardener/gardener/pkg/utils/version/version.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/modules.txt
Labels: area/open-source, area/usability, kind/enhancement, needs/ok-to-test, needs/lgtm, needs/review, platform/gcp, size/xs

#445 Enable the healthchecks for the csi-snapshot-validation Deployment
  pkg/controller/healthcheck/add.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#443 Renamed tutorial to folder name
  docs/tutorials/kubernetes-cluster-on-gcp-with-gardener/kubernetes-cluster-on-gcp-with-gardener.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, size/xs

#436 Bring-your-own-VPC is used
  pkg/apis/gcp/helper/scheme.go
  pkg/controller/bastion/actuator_delete.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/bastion/bastion_suite_test.go
  pkg/controller/bastion/options.go
  test/integration/bastion/bastion_test.go
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/m
