Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2022-02, with the labels that each got.

#383 Support for Kubernetes v1.23
  README.md
  charts/images.yaml
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/m, topology/garden, topology/seed, topology/shoot, merge/squash

#379 deletion of bastion blocked by ipv6
  pkg/controller/bastion/actuator.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/controller/bastion/bastion_suite_test.go
  pkg/controller/bastion/firewallrules.go
  pkg/controller/bastion/options.go
Labels: needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#380 Add support for sa token volume projection in the admission charts
  charts/gardener-extension-admission-gcp/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-gcp/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-gcp/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-gcp/charts/runtime/templates/serviceaccount.yaml
  charts/gardener-extension-admission-gcp/values.yaml
  docs/deployment.md
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/m

#390 Update valuesprovider.go
  pkg/controller/controlplane/valuesprovider.go
Labels: needs/ok-to-test, reviewed/lgtm

#389 Validate Worker serviceAccount when workers dataVolumes are not provided
  pkg/admission/validator/shoot.go
  pkg/apis/gcp/validation/shoot_test.go
  pkg/apis/gcp/validation/worker.go
  pkg/apis/gcp/validation/worker_test.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#392 Keep `cloud-controller-manager`'s `ClusterRoleBinding` on deletion
  charts/internal/shoot-system-components/charts/cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#393 Increase cpu resources for csi-driver
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#394 [release-v1.20] Automated cherry pick of #393: Increase cpu resources for csi-driver
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#395 Vendor gardener/gardener@v1.40.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/modules.txt
Labels: kind/bug, platform/gcp, reviewed/lgtm, size/xs
