Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2022-06, with the labels that each got.

#448 Vendor gardener/machine-controller-manager@v0.45.0
  go.mod
  go.sum
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/alicoud_machineclass_types.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#452 Re-enable vertical autoscaling for csi-driver-node
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#453 [release-v1.23] Automated cherry pick of #452: Re-enable vertical autoscaling for csi-driver-node
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#456 Change base image from alpine to distroless
  Dockerfile
Labels: area/open-source, area/security, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs, merge/squash

#455 Add parsers for csi-snapshot pods
  charts/gardener-extension-provider-gcp/templates/configmap-logging.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-controller.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-deployment.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-vpa.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#438 Added GPU support for GCP machines
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  docs/usage-as-end-user.md
  hack/api-reference/api.md
  pkg/apis/gcp/types_worker.go
  pkg/apis/gcp/v1alpha1/types_worker.go
  pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/gcp/validation/worker.go
  pkg/apis/gcp/validation/worker_test.go
  pkg/apis/gcp/zz_generated.deepcopy.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/quality, kind/api-change, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, platform/gcp, size/l
