Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2023-09, with the labels that each got.

#641 [release-v1.32] Automated cherry pick of #640: Update gcp-compute-persistent-disk-csi-driver
  charts/images.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#644 Update v1.27 conformance test coverage
  README.md
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#642 Updated doc for gpu specification
  docs/usage/usage.md
Labels: area/documentation, kind/enhancement, platform/gcp, reviewed/lgtm, size/xs

#648 Drop support for Shoots with Kubernetes version < 1.24
  README.md
  charts/gardener-extension-provider-gcp/values.yaml
  charts/images.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  docs/operations/operations.md
  example/controller-registration.yaml
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/open-source, kind/cleanup, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/m
