Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2023-03, with the labels that each got.

#569 Update v1.26 conformance test coverage
  README.md
Labels: needs/ok-to-test, needs/review, size/xs

#556 disable snat for non-overlay shoots
  go.mod
  go.sum
  pkg/admission/mutator/shoot.go
  pkg/admission/mutator/shoot_test.go
  pkg/controller/bastion/actuator.go
  pkg/controller/bastion/actuator_reconcile.go
  pkg/gcp/client/compute.go
  pkg/gcp/client/iam.go
  pkg/internal/infrastructure/infrastructure.go
  test/integration/infrastructure/infrastructure_test.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/cilium/types.go
  vendor/modules.txt
Labels: area/networking, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#575 Vendor `gardener@1.66.1` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#567 Add wait-for-csi-node annotation to csi-driver-node Pods
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#572 Update CSI driver to latest version
  charts/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#574 Make the `csi-snapshot-validation` Service topology-aware
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-service.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/s

#573 replace kaniko
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#579 Upgrade machine-controller-manager from v0.48.1 to v0.48.2
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#581 enable cleanup of snapshots
  .ci/pipeline_definitions
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#571 add support for eim
  docs/usage-as-end-user.md
  example/30-infrastructure.yaml
  hack/api-reference/api.md
  pkg/apis/gcp/types_infrastructure.go
  pkg/apis/gcp/v1alpha1/types_infrastructure.go
  pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/gcp/zz_generated.deepcopy.go
  pkg/internal/infrastructure/templates/main.tpl.tf
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
  test/integration/infrastructure/infrastructure_test.go
Labels: area/control-plane, kind/api-change, kind/enhancement, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, reviewed/do-not-merge, size/m
