Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2023-12, with the labels that each got.

#666 Update testmachinery image location
  .ci/pipeline_definitions
Labels: area/delivery, kind/task, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#672 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  charts/gardener-extension-admission-gcp/values.yaml
  charts/gardener-extension-provider-gcp/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, needs/review, size/s

#674 Add Kubernetes v1.28 conformance test badge
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/lgtm, platform/gcp, size/xs
