Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2023-11, with the labels that each got.

#658 Downgrade gcp-compute-persistent-disk-csi-driver from `v1.12.2` to `v1.11.1` as 1.12.x are not promoted on k8s.io
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#659 Vendor `gardener@v1.81.6`
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/imagevector/images.yaml
  vendor/github.com/gardener/gardener/pkg/utils/validation/features/featuregates.go
  vendor/github.com/gardener/gardener/test/framework/gardener_utils.go
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/README.md
  vendor/github.com/onsi/ginkgo/v2/ginkgo/outline/ginkgo.go
  vendor/github.com/onsi/ginkgo/v2/internal/group.go
  vendor/github.com/onsi/ginkgo/v2/internal/node.go
  vendor/github.com/onsi/ginkgo/v2/internal/writer.go
  vendor/github.com/onsi/ginkgo/v2/types/config.go
  vendor/github.com/onsi/ginkgo/v2/types/errors.go
  vendor/github.com/onsi/ginkgo/v2/types/types.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/tools/setup-envtest/README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#660 Add a label to the disks to associate them with a Shoot cluster
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#663 [release-v1.33] Automated cherry pick of #662: [ci:component:github.com/gardener/machine-controller-manager-provider-gcp:v0.17.0->v0.17.1]
  imagevector/images.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
