Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2023-05, with the labels that each got.

#588 Update gcp-compute-persistent-disk-csi-driver to v1.9.4
  charts/images.yaml
Labels: area/storage, kind/regression, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#590 [release-v1.29] Automated cherry pick of #588: Update gcp-compute-persistent-disk-csi-driver to v1.9.4
  charts/images.yaml
Labels: area/storage, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#591 Setting CSI GCP topology label on machine deployment creation to allo…
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/gcp/types.go
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs, area/auto-scaling

#592 Consider errors from NodesChecker for finding user related issues
  pkg/controller/healthcheck/add.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#593 [release-1.29] Consider errors from NodesChecker for finding user related issues
  pkg/controller/healthcheck/add.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#594 Adapt `NetworkPolicy`s
  charts/gardener-extension-admission-gcp/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-gcp/charts/runtime/templates/service.yaml
  charts/gardener-extension-provider-gcp/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager-svc.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-service.yaml
  example/controller-registration.yaml
  pkg/webhook/controlplane/ensurer.go
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#599 update go v1.20.4
  .test-defs/bastion-test.yaml
  .test-defs/infrastructure-test.yaml
  .test-defs/provider-gcp.yaml
  Dockerfile
  go.mod
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, size/xs

#602 Add cve categorziation for extension and admission controller
  .ci/pipeline_definitions
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs, area/compliance
