Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2023-08, with the labels that each got.

#633 Add `gardener-scheduler` region config example
  example/60-gardener-scheduler-region-configmap.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xl, area/scalability

#634 remove control plane limits
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#635 Fix the controlplane controller registration
  pkg/controller/controlplane/add.go
Labels: area/quality, kind/bug, kind/regression, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#636 Update gcp-compute-persistent-disk-csi-driver
  charts/images.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#638 Add support for projected volume kubeconfig
  charts/gardener-extension-admission-gcp/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-gcp/values.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/s

#639 Correct persona for end user tutorial
  .docforge/manifest.yaml
Labels: needs/review, reviewed/ok-to-test, size/xs

#640 Update gcp-compute-persistent-disk-csi-driver
  charts/images.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs
