Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2024-11, with the labels that each got.

#894 Address TODO after vendoring github.com/gardener/gardener@v1.106
  pkg/webhook/controlplane/ensurer.go
Labels: kind/cleanup, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#895 Update Kubernetes 1.31 conformance test coverage
  README.md
Labels: kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, reviewed/lgtm, size/xs

#899 fix missing pv rbac
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#900 [release-v1.40] Automated cherry pick of #899: fix missing pv rbac
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/xs

#892 Introduce gosec
  Makefile
  pkg/apis/config/loader/loader.go
  pkg/apis/gcp/validation/shoot.go
  pkg/apis/gcp/validation/shoot_test.go
  pkg/controller/worker/machines.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/s
