Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2024-07, with the labels that each got.

#792 Remove failing preStop hook in `node-driver-registrar`
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, needs/review, platform/gcp, size/xs

#800 Update k8s v1.30 conformance test coverage
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#794 [admission] Add `priorityClassName`
  charts/gardener-extension-admission-gcp/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-gcp/values.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/xs

#793 Fix hyperdisk specs validation
  hack/api-reference/api.md
  pkg/apis/gcp/types_worker.go
  pkg/apis/gcp/v1alpha1/types_worker.go
  pkg/apis/gcp/validation/worker_test.go
  pkg/controller/worker/machines.go
Labels: area/quality, kind/api-change, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, platform/gcp, reviewed/lgtm, size/s

#805 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, size/s

#809 Inserts `Architecture` from worker to machineclass
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/s

#798 Prepare switch to upstream CCM
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
Labels: area/control-plane, kind/technical-debt, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#812 Update vpa crd
  example/20-crd-vpa.yaml
Labels: kind/technical-debt, needs/ok-to-test, needs/review, needs/second-opinion, platform/gcp, size/xl, area/testing

#813 fix an issue where shoots would be migrated to flow during cp-migration
  pkg/webhook/infrastructure/mutator.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, platform/gcp, size/xs

#814 [release v1.37] fix an issue where shoots would be migrated to flow during cp-migration
  pkg/webhook/infrastructure/mutator.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs
