Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2024-01, with the labels that each got.

#678 set COMPONENT_PREFIXES env variable to fix upgrade PRs
  .ci/component_descriptor
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#668 Fix recipe for locally running the extension controller
  Makefile
  example/00-componentconfig.yaml
  hack/hook-me.sh
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#681 update image building rules
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, size/xs

#682 fix hook-me script
  Makefile
  hack/dev-setup-admission-gcp.sh
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/s

#685 update csi driver
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, size/xs

#690 fix unknown flag
  Makefile
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, platform/gcp, reviewed/lgtm, size/xs

#667 Add support for min cpu platform to worker config
  charts/internal/machineclass/templates/machineclass.yaml
  hack/api-reference/api.md
  pkg/apis/gcp/types_worker.go
  pkg/apis/gcp/v1alpha1/types_worker.go
  pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/gcp/zz_generated.deepcopy.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/s

#687 Make it possible to disable defaulting of storage classes
  charts/internal/shoot-storageclasses/templates/storageclasses.yaml
  charts/internal/shoot-storageclasses/values.yaml
  docs/usage/usage.md
  example/30-controlplane.yaml
  hack/api-reference/api.md
  pkg/apis/gcp/types_controlplane.go
  pkg/apis/gcp/v1alpha1/defaults.go
  pkg/apis/gcp/v1alpha1/defaults_test.go
  pkg/apis/gcp/v1alpha1/types_controlplane.go
  pkg/apis/gcp/v1alpha1/zz_generated.conversion.go
  pkg/apis/gcp/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/gcp/v1alpha1/zz_generated.defaults.go
  pkg/apis/gcp/zz_generated.deepcopy.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/storage, kind/api-change, kind/enhancement, needs/ok-to-test, platform/gcp, reviewed/lgtm, size/l

#693 Support for Kubernetes v1.29
  README.md
  imagevector/images.yaml
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, reviewed/ok-to-test, size/xs, topology/garden, topology/seed, topology/shoot, merge/squash

#669 Enhance labels for gcp workers and disks
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
