Repository gardener/gardener-extension-provider-gcp, pull requests merged in 2024-08, with the labels that each got.

#818 Fix infra status egress CIDRs
  pkg/controller/infrastructure/actuator.go
Labels: area/networking, kind/bug, needs/ok-to-test, platform/gcp, reviewed/ok-to-test, reviewed/lgtm, size/xs

#819 Fix infra status egress CIDRs
  pkg/controller/infrastructure/actuator.go
Labels: area/networking, kind/bug, needs/ok-to-test, needs/review, platform/gcp, size/xs

#789 Add object selector to controlplane webhook with version constraint
  cmd/gardener-extension-provider-gcp/app/app.go
  pkg/cmd/options.go
  pkg/webhook/controlplane/add.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, reviewed/ok-to-test, size/s

#815 Publish separate admission Helm charts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, needs/review, platform/gcp, size/xs
